version: "3"
services:
    nginx:
        image: nginx:1.12.1-alpine
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./wwwroot:/home/www-data #如果不加这行就会出现 ->  issues/2
            - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/nginx/vhost:/etc/nginx/conf.d
    php:
        build:
            context: ./app/php5.6
            dockerfile: Dockerfile
        ports:
            - "3690:3690"
        volumes:
            - ./svn:/home/svn
            - ./script/start.sh:/var/www/html/start.sh
            - ./wwwroot:/home/www-data
            - ./app/php5.6/conf/php.ini:/usr/local/etc/php/php.ini
        command: ./start.sh
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test123"
