version: "3"
services:
    nginx:
        image: nginx:1.12.1-alpine
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./wwwroot:/home/www-data #如果不加这行就会出现 ->  issues/2
            - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/nginx/vhost:/etc/nginx/conf.d
    php:
        build:
            context: ./app/php5.6
            dockerfile: Dockerfile
        volumes:
            - ./svn:/home/svn
            - ./wwwroot:/home/www-data
            - ./app/php5.6/conf/php.ini:/usr/local/etc/php/php.ini
    svn:
        image: svn
        build:
            context: ./app/svn
            dockerfile: Dockerfile
        ports:
            - "3690:3690"
        volumes:
            - ./svn:/var/opt/svn
