version: "3"
services:
    nginx:
        image: nginx:1.12.1-alpine
        ports:
            - "80:80"
        links:
            - php
            - php5.6
            - php5.3
            - node
        volumes:
            - ./wwwroot:/home/www-data #如果不加这行就会出现 ->  issues/2
            - ./app/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./app/nginx/vhost:/etc/nginx/conf.d
#构建本地Dockerfile
#php:
#    build:
#        context: ./app/php7.2
#        dockerfile: Dockerfile
    php:
        image: hellomjw/php:laravel
        volumes:
            - ./wwwroot:/home/www-data
            - ./app/php7.2/conf/php.ini-development:/usr/local/etc/php/php.ini
    php5.6:
        image: hellomjw/php:5.6
        volumes:
            - ./wwwroot:/home/www-data
            - ./app/php5.6/conf/php.ini:/usr/local/etc/php/php.ini
    php5.3:
        image: hellomjw/php:ks-5.3.28
        volumes:
            - ./wwwroot:/home/www-data
    # node:
    #     command: npm start
    #     image: node:9.2-alpine
    #     working_dir: /home/www-data
    #     volumes:
    #         - ./wwwroot:/home/www-data
    mysql5.6:
        image: mysql:5.6
        ports:
            - "3306:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_USER: "test"
            MYSQL_PASSWORD: "test123"
